name: hooper-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - git-lfs
  - pip:
    - torch
    - torchvision
    - numpy
    - opencv-python
    - detectron2
    - sam-2
    - ultralytics
    - supervision
    - firebase-admin
    - fastapi
    - uvicorn
    - python-dotenv
    - requests
    - gdown
    - ffmpeg-python
    - pytube
    - av
    - matplotlib
    - pandas
    - scikit-learn
    - scipy
    - tqdm
    - pyyaml
    - pillow
    - shapely
    - tabulate
    - termcolor
    - yacs
    - hydra-core
    - omegaconf
    - fvcore
    - iopath
    - pycocotools
    - tensorboard
    - tensorboard-data-server
    - torchaudio
    - triton
    - typing-extensions
    - typing-inspection
    - ultralytics-thop
    - werkzeug
    - yarl
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.16.0=he5ede1b_6
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - eigen=3.4.0=h4bd325d_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=10.2.0=hf296adc_0
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.78.4=hdc74915_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - opencv=4.10.0=py310h32367a4_5
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
